### ISSUE TITLE
Fails to install required modules from requirements.txt

### ISSUE THREAD

**Issue by sandmanhuck** [h4de5/volumio-nfc#1]
Using Volumio 2.907 with this library, I am unable to install the required modules listed in requirements.txt when using the master branch of this repository. 

Here is the output I see:
```bash
volumio@volumio:~/volumio-nfc$ git status                             
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
volumio@volumio:~/volumio-nfc$ python3 -m pip install requirements.txt 
Downloading/unpacking requirements.txt
  Could not find any downloads that satisfy the requirement requirements.txt
Cleaning up...
No distributions at all found for requirements.txt
Storing debug log for failure in /home/volumio/.pip/pip.log
```

`git log` tells me the most recent commit is 23674a54d775e05d73837b74964225d166bf3577. There are no releases or tags on the repository, so I hope this commit ID helps you identify the version of your code that I have.

This means I am unable to use your library. Please could you look into this, or perhaps document the installation and setup requirements in more detail?

**Comment by sandmanhuck** [comment]
It seems that you need to update requirements.txt to list `configparser` instead of `parseconfig`, which is the name of a local python file and not of a module listed on https://pypi.org

**Comment by h4de5** [comment]
I must admit, i haven't done much since the initial setup. at the moment I cannot even run it anymore, because a volumio update a while has broken the file indexer and I can't get it back working :\
